// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Zse6qB7v0z-faMfr3LcC71iMrGOTTD4',
    appId: '1:405437331830:web:907aa6c97610ef5c20e257',
    messagingSenderId: '405437331830',
    projectId: 'ngelesin',
    authDomain: 'ngelesin.firebaseapp.com',
    storageBucket: 'ngelesin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChFDoHdPs7FcAa4XHXOcOxh-b1rthEM1A',
    appId: '1:405437331830:android:f594e695d0bc865620e257',
    messagingSenderId: '405437331830',
    projectId: 'ngelesin',
    storageBucket: 'ngelesin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpknBpHbHhplFdFUIuna2D81GxyDehm6c',
    appId: '1:405437331830:ios:44340bdaf378a15220e257',
    messagingSenderId: '405437331830',
    projectId: 'ngelesin',
    storageBucket: 'ngelesin.firebasestorage.app',
    iosBundleId: 'com.example.ngelesin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpknBpHbHhplFdFUIuna2D81GxyDehm6c',
    appId: '1:405437331830:ios:44340bdaf378a15220e257',
    messagingSenderId: '405437331830',
    projectId: 'ngelesin',
    storageBucket: 'ngelesin.firebasestorage.app',
    iosBundleId: 'com.example.ngelesin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6Zse6qB7v0z-faMfr3LcC71iMrGOTTD4',
    appId: '1:405437331830:web:2f2bcda9e836175220e257',
    messagingSenderId: '405437331830',
    projectId: 'ngelesin',
    authDomain: 'ngelesin.firebaseapp.com',
    storageBucket: 'ngelesin.firebasestorage.app',
  );
}
